### ISSUE TITLE
other time intervals

### ISSUE THREAD

**Issue by pi-phi** [joachimruhs/booking#1]
is it possible to configure other timeintervals than whole hours?

eiterh directly

e.g.:
7:00
7:15
7:30
7:45
 : 
18:30
18:45
19:00

 or with something like a 'translation'?

timeslot
No. - scheduled Time
00 - 07:00
01 - 07:15
02 - 07:30
03 - 07:45
 :        : 
46 - 18:30
47 - 18:45
48 - 19:00

and also: is it possible to have different active times per day of week?

mon 7:00-19:00
tue  8:00-18:00
wed 8:00- 12:00, 15:00-18:00
thu 8:00-18:00
fri 8:00-13:00
sat none
sun none

**Comment by joachimruhs** [comment]
Hi,
at the moment not possible...
But different operating hours per weekday may be a future option…

Regards

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi there, 

this functionality is needed here, too. Once per week on weekday X every Y minutes within time range ZZ:ZZ and ZZ:ZZ. Ideally with an option for a time range for a break/pause. ;)

My question: Any chance of such a functionality in the future? If not, do you think it's hard to implement it in general? I'm thinking of a fork request.

Cheers
