### ISSUE TITLE
Why does Booking disable eID feature?

### ISSUE THREAD

**Issue by tobiasschaeferptb** [joachimruhs/booking#2]
Hi Joachim,

I use EXT:caretaker_instance (3.0.3) on the same TYPO3 (9.5.20) where EXT:booking (1.4.5) is installed. caretaker_instance relies on the eID feature.
This feature is disabled by booking in booking/Configuration/RequestMiddlewares.php
return [
    'frontend' => [
        'typo3/cms-frontend/eid' => [
            **'disabled' => true,**
        ],

What is the reason for this and could it be solved in a different way?

Cheers, Tobias

**Comment by joachimruhs** [comment]
Hello,
booking uses the new Middleware PSR-15. Try to set 'disabled' => false

**Comment by tobiasschaeferptb** [comment]
Sorry, I didn't mentioned that changing disabled to false fixes the problem for caretaker_instance.
I wasn't sure what are the consequences for booking if I change it.

**Comment by joachimruhs** [comment]
I tested booking with 'disabled' => false. It still works.
Closing the issue
