### ISSUE TITLE
Raise PHP 8.x compatibility

### ISSUE THREAD

**Issue by josefglatz** [joachimruhs/booking#3]
Actually many classic PHP 8.x relevant warnings are thrown.

**Comment by joachimruhs** [comment]
I have published version 1.8.2. Pls have a look on that.

**Comment by josefglatz** [comment]
haha thank you. Already started with a fork on the same tasks in the morning. you were quicker!. Will recheck asap! (its just a side project...)

**Comment by josefglatz** [comment]
@joachimruhs thanks for the actual fixes. There are other errors:

A) Just when you visit a page with the plugin without clicking on anything else in the plugin:

> `Core: Error handler (FE): PHP Warning: Undefined array key "bookobjectUid" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 668`

B) Clicking on the next month works as expected beside the thrown errors:

> `Core: Error handler (FE): PHP Warning: Undefined array key "year" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 617`
>
> `Core: Error handler (FE): PHP Warning: Undefined array key "month" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 620`
>
> `Core: Error handler (FE): PHP Warning: Undefined array key "month" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 642`
>
> `Core: Error handler (FE): PHP Warning: Undefined array key "year" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 643`
>
> `Core: Error handler (FE): PHP Warning: Undefined array key "bookobjectUid" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 668`
>
> `Core: Error handler (FE): PHP Warning: Undefined array key "month" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 736`
> 
> `Core: Error handler (FE): PHP Warning: Undefined array key "year" in /var/www/html/public/typo3conf/ext/booking/Classes/Controller/BookobjectController.php line 737`

**Comment by joachimruhs** [comment]
Hi,
I can't reproduce these errors.
You can test it here https://typo11.joachim-ruhs.de/extensions/booking and 
fe user femueller / hallo1

The debug preset is debug.

**Comment by josefglatz** [comment]
Error appears when you set TypoScript constant `plugin.tx_booking.settings.defaultCalendar = week`

**Comment by joachimruhs** [comment]
Ok,
fixed them and published booking-1.8.3

**Comment by josefglatz** [comment]
Thank you. So far it looks fine! The club is very happy!
