### ISSUE TITLE
Error in BookobjectController - function processPostRequest

### ISSUE THREAD

**Issue by jacques2017** [joachimruhs/booking#9]
Hi,
in TYPO3 12 I get an error on line 254 in BookobjectController:

`
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "typo3Language" in .../web/vendor/wsr/booking/Classes/Controller/BookobjectController.php line 247
in .../web/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php line 138

        }

        $message = self::ERROR_LEVEL_LABELS[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }

        $message = $this->getFormattedLogMessage($message);

at TYPO3\CMS\Core\Error\ErrorHandler->handleError()
in .../web/vendor/wsr/booking/Classes/Controller/BookobjectController.php line 247
                $this->language = $siteConfiguration['languages'][$i]['typo3Language'];
            }
        }
        
        
`
Better use the Api in this case:
```
				$siteLanguage = $this->request1->getAttribute('language');
				$this->language = $siteLanguage->getTypo3Language();

```

**Comment by joachimruhs** [comment]
Thx for reporting, 
I just made a new version 2.1.3

**Comment by jacques2017** [comment]
Thx. Please check your html-Templates. With Composer-Installation the path to the images are wrong.
Better use:
```
  <f:variable name="uriImg"><f:uri.image src="EXT:booking/Resources/Public/Icons/actions-delete.svg" /></f:variable>
                                      <img class="deleteBooking bkPlus" src="{uriImg}" bookUid="{booking.uid}" />
```
instead of

`									<img class="deleteBooking bkPlus" src="/typo3conf/ext/booking/Resources/Public/Icons/actions-delete.svg" bookUid="{booking.uid}" /></td>
`
And there is a double </td> at the delete-icon

**Comment by joachimruhs** [comment]
Thx for reporting,
I just made a new version 2.1.4

**Comment by jacques2017** [comment]
Thx
